id: 1a2cad505d534c2fb99fd5fc6202b33b
initial_creation_type: ocr
source_metadata:
  volumes:
    9b8edd63d66e42f9a6c9f162be879e3a:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: དམ་ཚིག་ཐམས་ཅད་བསྡུས་པ།
      total_pages: 1349
      volume_number: 41
