id: D775A7C70
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:33:48+00:00'
last_modified: '2022-05-26T14:29:03.844381+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f470:
      image_group_id: I1PD95886
      title: དམ་ཚིག་ཐམས་ཅད་བསྡུས་པ།
      total_pages: 1349
      order: 41
      base_file: f470.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
